name: Gradle

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13 ]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4.1.2
      - name: Set up JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
          check-latest: true
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3.1.0
        with:
          gradle-version: current
          arguments: packageDistributionForCurrentOS --warning-mode all

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ matrix.os }}-artifact
          path: build/compose/binaries/main/*

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Set up JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
          check-latest: true
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3.1.0
        with:
          gradle-version: current
          arguments: build

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: artifact
          path: |
            build/libs
